version: '3.8'

services:

  php:
    build: ./php
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: postgres_postgis_collab
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: treecolor
      POSTGRES_PASSWORD: treecolor
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
