services:
  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: postgres_postgis_collab
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=treecolor
      - POSTGRES_PASSWORD=treecolor
      - POSTGRES_DB=zones
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: